- platform-hub-api/config/environments/production.rb
- platform-hub-api/config/initializers/filter_parameter_logging.rb
- API: in `production` environments only log INFO and above
- API: filter out some commonly used fields during logging to prevent values showing up in logs
@marcinc (and anyone else) – can you think of any more fields that should be filtered out during logging?
> Logging and security updates

- platform-hub-api/app/controllers/support_request_templates_controller.rb
- platform-hub-api/app/models/support_request_template.rb
- platform-hub-api/app/services/support_request_formatter_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/support_request_templates_controller_spec.rb
- platform-hub-api/spec/routing/support_request_templates_routing_spec.rb
- platform-hub-web/src/app/help/support/requests/support-requests-form.component.js
- platform-hub-web/src/app/help/support/requests/support-requests-form.html
- platform-hub-web/src/app/help/support/requests/support-requests-overview.component.js
- platform-hub-web/src/app/help/support/requests/support-requests-overview.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- Web: pop up a dialog with a link to the GitHub issue, after submitting a support request
- Make it clearer to the user how to get to their support requests
- API: when submitting a support request to GitHub, add the user's details in the title text
> Support requests improvements

- platform-hub-api/app/models/hash_record.rb
- platform-hub-api/db/migrate/20170322132009_create_hash_records.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/factories/hash_records.rb
- platform-hub-api/spec/models/hash_record_spec.rb
- platform-hub-api/spec/models/support_request_template_spec.rb
We'll be using this in upcoming features, for two particular use cases:
1. The server needs to store some data in a black box fashion and doesn't care about the contents and schema of that data – e.g. application config specifically for the client, only allowed to be set by admins.
1. The server needs to store some JSON data that doesn't need dedicated table(s).
> Provide a very simple Hash (a.k.a. dictionary) record store, for arbitrary chunks of data

- platform-hub-web/src/.eslintrc.js
- platform-hub-web/src/app/shared/model/platform-themes-list.js
- platform-hub-web/src/app/shared/util/array-util.service.spec.js
- platform-hub-web/src/app/shared/util/array-utils.service.js
- platform-hub-web/src/app/shared/util/util.module.js
Took this opportunity to move the array-splitting-and-sorting-by-specified-ids functionality into it's own service, and writing tests for it.
> Web: fix ordering bug in the platform themes list

- platform-hub-web/src/app/home/home.html
- Logged out users: only see a login button
- Logged in users: only see the list of platform themes
i.e. this commit removes the FAQs from the homepage, and changes the login text to a login button
> Web: simplify the homepage

- platform-hub-api/app/controllers/platform_themes_controller.rb
- platform-hub-api/app/serializers/platform_theme_serializer.rb
- platform-hub-api/db/migrate/20170410142703_add_resources_field_to_platform_themes.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/platform_themes_controller_spec.rb
- platform-hub-api/spec/factories/platform_themes.rb
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-form.component.js
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-form.html
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-list.html
- platform-hub-web/src/app/platform-themes/editor/platform-themes-resource-kind-fields.component.js
- platform-hub-web/src/app/platform-themes/editor/platform-themes-resource-kind-fields.html
- platform-hub-web/src/app/platform-themes/platform-themes-page.component.js
- platform-hub-web/src/app/platform-themes/platform-themes-page.html
- platform-hub-web/src/app/platform-themes/platform-themes.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/model.module.js
- platform-hub-web/src/app/shared/model/platform-themes-resource-kinds.js
- Admins can fully manage (create, edit and delete) all actions (aka "resources") for a particular platform theme, within the hub.
- Actions can link to an existing support request form.
- Actions can link to pages within the hub.
- Actions can link to external resources.
- Actions can be plain text (e.g. a placeholder for something upcoming, or informational text).
- Actions have a descriptor to show to users when they see it in the platform theme (set by admins).
- Admins can switch an action from one type to another (to help easily migrate to new functionality / external resources).
- Admins can reorder actions within a platform theme.
---
**TODO**:
> Platform themes now have a list of "resources" (aka "actions") that can be configured by an admin

- platform-hub-api/app/controllers/identity_flows_controller.rb
- platform-hub-api/spec/controllers/identity_flows_controller_spec.rb
Previously, we would end up with a Rails "double render" error since we didn't return early after catching the error and setting up the error response.
> API: fix the error handling in the `IdentityFlowsController`

- platform-hub-web/package.json
- platform-hub-web/src/app/app-settings/app-settings-form.component.js
- platform-hub-web/src/app/app-settings/app-settings-form.html
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/home/home.component.js
- platform-hub-web/src/app/home/home.html
- platform-hub-web/src/app/shared/model/app-settings.js
- platform-hub-web/yarn.lock
- This can be used to provide some high level information about the platform, complimenting the platform theme boxes
- Shown to both logged in users and visitors (i.e. public)
- Hyperlinks, external images and rich text are supported (via the [medium-editor](http://yabwe.github.io/medium-editor/) component)
> Admins can now configure some overview text for the homepage

- platform-hub-api/app/controllers/app_settings_controller.rb
- platform-hub-api/app/controllers/concerns/authentication.rb
> API: handle expired auth tokens

- platform-hub-api/app/controllers/announcements_controller.rb
- platform-hub-api/app/models/announcement.rb
- platform-hub-api/app/serializers/announcement_serializer.rb
- platform-hub-api/db/migrate/20170602101700_create_announcements.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/announcements_controller_spec.rb
- platform-hub-api/spec/factories/announcements.rb
- platform-hub-api/spec/models/announcement_spec.rb
Given the original code for this was merged in earlier today, hopefully this cheeky rename won't affect anything (as it hasn't yet been deployed to persistent environment).
> API: rename `published_at` to `publish_at` to make more sense!

- platform-hub-web/src/app/layout/shell.html
This change makes sure they only render once the Me data has been fetched from the API.
> Web: fix flickering in/out of the onboarding prompts

- platform-hub-api/app/controllers/me_controller.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/me_controller_spec.rb
- Added additional route to show identity, returning a json object
- Added 'before_action' on delete and show identity, to first attempt a get and return 404 on failure
- Updated controller tests
> [ACPBoard #378] Bugfix 500 Server Error deleting missing identities

- platform-hub-web/src/app/identities/identities-manager.html
- platform-hub-web/src/app/onboarding/services-onboarding.html
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/identities/identities-list.html
This is so the final and important step of the flow is shown to the user more prominently – before this, a long "other services" list would hide the section below unless the user rememebered to scroll.
> Web: collapse the list of "other services" on the services onboarding page

- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
Before, it was not immediately obvious to an admin why an announcement was not visible in the "Global Announcements" section of the hub. With this change, hopefully the unpublished nature makes things clearer.
> Web: unpublished announcements are now clearer in the announcements editor

- platform-hub-api/app/controllers/announcements_controller.rb
- platform-hub-api/app/mailers/announcement_mailer.rb
- platform-hub-api/app/models/announcement.rb
- platform-hub-api/app/services/announcement_template_formatter_service.rb
- platform-hub-api/app/services/announcements_processor_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/announcements_controller_spec.rb
- platform-hub-api/spec/factories/announcements.rb
- platform-hub-api/spec/models/announcement_spec.rb
- platform-hub-api/spec/routing/announcements_routing_spec.rb
- platform-hub-api/spec/services/announcements_processor_service_spec.rb
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.component.js
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/announcements.js
This change also includes (to address some side effects of allowing redelivery):
- better specs for the `AnnouncementsProcessorService`
- better logic for when to update the template definitions for an announcement (i.e. now it only updates them for non-published announcements)
- better specs for the `Announcement` model, for the abovementioned change
> Admins can now resend an existing published announcement

- platform-hub-api/app/services/kubernetes/token_file_service.rb
- platform-hub-api/spec/services/kubernetes/token_file_service_spec.rb
Kube tokens file generator shouldn't expect groups to be always present. They've been made optional.
> Kube tokens file generator handles tokens without groups

- platform-hub-api/spec/services/announcements_processor_service_spec.rb
I'm genuinely not sure how that test ever passed; it has been flakey lately in latest CI, which may have exposed the timing issues;
> API: fix a dodgy test

- platform-hub-web/src/app/shared/model/user-scopes.js
- blank `scope` is now handled
- default is now to show
> Web: fix scope visibility… (fixes #126)

- platform-hub-api/README.md
- platform-hub-api/app/controllers/kubernetes/robot_tokens_controller.rb
- platform-hub-api/app/models/kubernetes_robot_token.rb
- platform-hub-api/app/serializers/identity_serializer.rb
- platform-hub-api/app/serializers/kubernetes_robot_token_serializer.rb
- platform-hub-api/app/services/kubernetes/robot_token_service.rb
- platform-hub-api/app/services/kubernetes/static_token_service.rb
- platform-hub-api/spec/controllers/kubernetes/robot_tokens_controller_spec.rb
- platform-hub-api/spec/services/kubernetes/robot_token_service_spec.rb
- platform-hub-api/spec/services/kubernetes/static_token_service_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-list.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/identities/identities-list.html
This provides the ability for admins to associate robot tokens with users, and then for these tokens to be shown on the user's Connected Identities page.
This is an interim solution, until we have the new project and services self-serve tokens feature ready.
> Interim solution for robot tokens - associate with users

- platform-hub-api/app/controllers/kubernetes/groups_controller.rb
- platform-hub-api/app/models/allocation.rb
- platform-hub-api/app/models/concerns/allocatable.rb
- platform-hub-api/app/models/concerns/allocation_receivable.rb
- platform-hub-api/app/models/kubernetes_group.rb
- platform-hub-api/app/models/project.rb
- platform-hub-api/app/models/service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20171010111440_create_allocations.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/kubernetes/groups_controller_spec.rb
- platform-hub-api/spec/factories/allocations.rb
- platform-hub-api/spec/routing/kubernetes_groups_routing_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-groups-detail.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-groups-detail.html
- platform-hub-web/src/app/projects/projects.module.js
- platform-hub-web/src/app/projects/services/project-service-selector-popup.controller.js
- platform-hub-web/src/app/projects/services/project-service-selector-popup.html
- platform-hub-web/src/app/projects/services/project-service-selector-popup.service.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/kubernetes-groups.js
Note: this doesn't yet include a way to list and modify these allocations. Coming soon!
> Hub admins can now allocate Kubernetes groups to projects or project services

- platform-hub-api/app/controllers/projects_controller.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/routing/projects_routing_spec.rb
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/projects.js
- Added a new endpoint for checking whether the logged in user has a specified role in a project
- Used this in the project detail page to determine whether to set the `isProjectManager` flag on that page
- Also changed the flow around in the projct detail page to first check admin status and then only continue if that was successful (this way if the API is down, or something is not quite right, we fail early)
> Refactor the way we do project manager checks

- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/factories/kubernetes_clusters.rb
- platform-hub-api/spec/factories/kubernetes_groups.rb
- platform-hub-api/spec/factories/kubernetes_tokens.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
- platform-hub-api/spec/services/kubernetes/token_file_service_spec.rb
This ensures that only allocated clusters and RBAC groups can be used when creating kubernetes tokens of kind `robot`.
---
**Note:** I've gone for a slightly less performant implementation in order to (hopefully) provide a more readable and better structured solution to the different validations. Given that a) tokens won't be created/updated that often, and b) we assume that at most there only be a few groups assigned to a token, this implementation should be "okay" (until proven otherwise :)).
> Backend: model validations for checking cluster and groups for kube robot tokens

- platform-hub-api/app/jobs/tokens_sync_job.rb
- platform-hub-api/app/services/feature_flag_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/lib/tasks/kubernetes.rake
- platform-hub-api/spec/jobs/tokens_sync_job_spec.rb
- platform-hub-api/spec/routing/kubernetes_sync_routing_spec.rb
- platform-hub-api/spec/routing/kubernetes_tokens_routing_spec.rb
- platform-hub-api/spec/services/feature_flag_service_spec.rb
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/app.routes.spec.js
- platform-hub-web/src/app/app.run.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.html
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/shared/model/feature-flags.js
This provides finer grained control over the Kubernetes tokens features.
Note:
- The existing `kubernetes_tokens` flag still exists and is used as a "master" toggle of all Kubernetes tokens features in the hub.
- Thus, this commit adds support for configuring and inspecting multiple feature flags for UI routes, shell nav and API endpoints.
- The tokens privilege expirer job will run regardless of the new `kubernetes_tokens_escalate_privilege` flag (but can be turned off using the existing `kubernetes_tokens` flag).
> New feature flags for tokens sync + tokens escalation of privileges

- platform-hub-api/app/controllers/app_settings_controller.rb
- platform-hub-api/spec/controllers/app_settings_controller_spec.rb
- platform-hub-web/src/app/app.run.js
Only the platform name and platform overview text should be made public to non-logged in users.
> Only return certain fields in the /app_settings API when not logged in

- platform-hub-api/app/models/audit.rb
This is to prevent any potential leaking of audit data into logs.
> Backend: only output the audit message to logs in debug mode

- platform-hub-api/lib/tasks/kubernetes.rake
We can now manage clusters directly in the UI.
> Backend: remove the `kubernetes:cluster:*` rake tasks

- platform-hub-api/app/controllers/concerns/kubernetes_groups_sub_collection.rb
- platform-hub-api/app/controllers/kubernetes/groups_controller.rb
- platform-hub-api/app/controllers/kubernetes/tokens_controller.rb
- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/kubernetes/groups_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
- platform-hub-api/spec/routing/kubernetes_groups_routing_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-token-escalate-privilege-popup.controller.js
- platform-hub-web/src/app/kubernetes/kubernetes-token-escalate-privilege-popup.html
- platform-hub-web/src/app/kubernetes/kubernetes-token-escalate-privilege-popup.service.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.html
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/kubernetes-groups.js
- platform-hub-web/src/app/shared/model/kubernetes-tokens.js
- platform-hub-web/src/app/shared/model/projects.js
Given that tokens are now scoped to projects only (and only using groups that are allowed within that project), this commit now scopes the escalation of privileges to just the privileged groups for that project on that token.
This also adds the escalate privilege button for user tokens within projects (for project admins only).
Important caveat: when a token has escalated privileges, you can't currently edit that token until the privilege has expired. This is due to the privileged group being in the `groups` field, and the form/API not allowing this.
> Re-do the token escalation of privileges to restrict it per project

- platform-hub-api/app/models/kubernetes_group.rb
- platform-hub-api/spec/models/kubernetes_group_spec.rb
This atomically updates all tokens that have the updated group
> Backend: handle Kube RBAC group rename

- platform-hub-api/app/models/kubernetes_group.rb
- platform-hub-api/spec/models/kubernetes_group_spec.rb
This atomically updates all tokens that have the removed group
> Backend: handle Kube RBAC group deletions

- platform-hub-api/app/controllers/projects_controller.rb
- platform-hub-api/app/models/project.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
Note: as part of this, we eager load the `membership.user` field, prevent N+1 queries.
> API: order the project memberships by user name

- platform-hub-api/app/models/allocation.rb
- platform-hub-api/app/models/concerns/allocatable.rb
- platform-hub-api/app/models/concerns/allocation_receivable.rb
- platform-hub-api/app/models/kubernetes_cluster.rb
- platform-hub-api/app/models/kubernetes_group.rb
- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/app/models/project.rb
- platform-hub-api/app/models/project_membership.rb
- platform-hub-api/app/models/service.rb
- platform-hub-api/app/models/user.rb
- platform-hub-api/spec/factories/kubernetes_tokens.rb
- platform-hub-api/spec/integration/tokens_deletion_integration_spec.rb
- platform-hub-api/spec/models/kubernetes_group_spec.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
> Handle deletions of projects, services, allocations, groups, clusters and tokens

- platform-hub-api/app/controllers/kubernetes/namespaces_controller.rb
- platform-hub-api/app/models/kubernetes_namespace.rb
- platform-hub-api/app/serializers/kubernetes_namespace_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20171127115843_create_kubernetes_namespaces.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/kubernetes/namespaces_controller_spec.rb
- platform-hub-api/spec/factories/kubernetes_namespaces.rb
- platform-hub-api/spec/models/kubernetes_namespace_spec.rb
- platform-hub-api/spec/routing/kubernetes_namespaces_routing_spec.rb
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/kubernetes/kubernetes-namespaces-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-namespaces-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-namespaces-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-namespaces-list.html
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes.module.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/projects/services/project-services-detail.component.js
- platform-hub-web/src/app/projects/services/project-services-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/kubernetes-namespaces.js
- platform-hub-web/src/app/shared/model/model.module.js
Note: there's currently no relationship/interaction between RBAC groups and namespaces within the hub – we can solve this in a later PR (depending on _if_ and _how_ we might want to do that).
> Hub admins can now manage Kubernetes namespaces, assigned to project services

- platform-hub-api/app/controllers/costs_reports_controller.rb
- platform-hub-api/app/models/costs_report.rb
- platform-hub-api/app/serializers/costs_report_serializer.rb
- platform-hub-api/app/services/project_bills_query_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20171214165427_add_published_at_to_costs_reports.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/costs_reports_controller_spec.rb
- platform-hub-api/spec/factories/costs_reports.rb
- platform-hub-api/spec/models/costs_report_spec.rb
- platform-hub-api/spec/routing/costs_reports_routing_spec.rb
- platform-hub-web/src/app/costs-reports/costs-reports-detail.html
- platform-hub-web/src/app/costs-reports/costs-reports-form.html
- platform-hub-web/src/app/costs-reports/costs-reports-list.component.js
- platform-hub-web/src/app/costs-reports/costs-reports-list.html
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/costs-reports.js
… before they get shown to projects.
Note: once published, a report cannot be edited, nor recreated via the reports form (though you can still explicitly delete it and recreate it in two separate steps, as a special case capability).
> Add an extra publish step for Costs Reports

- platform-hub-web/src/app/projects/services/project-services-detail.html
… only hub admins can view and manage these at the moment.
Note: the API was still returning a 403, so this is purely a UI fix.
> Web: fix namespaces tab visibility

- platform-hub-api/app/serializers/identity_serializer.rb
- platform-hub-web/src/app/app.scss
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/identities/identities-list.html
- platform-hub-web/src/app/shared/kubernetes-identity-tokens-popup.controller.js
- platform-hub-web/src/app/shared/kubernetes-identity-tokens-popup.html
- platform-hub-web/src/app/shared/kubernetes-identity-tokens-popup.service.js
- platform-hub-web/src/app/shared/shared.module.js
The "Show tokens" button the Connected Identities page now pops open a dialogue, where you can view all your tokens, in a better and more user friendly layout.
> Web: revamped user experience for viewing your own Kubernetes tokens

- platform-hub-web/src/app/app.run.js
- platform-hub-web/src/app/shared/api-interceptor.service.js
- platform-hub-web/src/app/shared/events.factory.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
Previously, we would still continue to load up the view/component, whereas now we redirect to the homepage on any 404 response from the API.
> Web: handle 404 responses from the API in a better way

- platform-hub-api/app/models/user.rb
- platform-hub-api/app/services/agents/git_hub_agent_service.rb
- platform-hub-api/app/services/support_request_formatter_service.rb
- platform-hub-api/app/services/user_activation_service.rb
- platform-hub-api/spec/factories/identities.rb
- platform-hub-api/spec/services/agents/git_hub_agent_service_spec.rb
- platform-hub-api/spec/services/user_activation_service_spec.rb
Note: this is a "non blocking" operation, in that if onboard/offboard fails for whatever reason then the activation/deactivation of the user still continues.
> Backend: onboard/offboard to Github when deactivating a user

- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/shared/hub-api/api-helpers.factory.js
- platform-hub-web/src/app/shared/hub-api/api-request-builders.factory.js
- platform-hub-web/src/app/shared/hub-api/hub-api.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- Moved all general API helpers into a separate `apiHelpers` service.
- Added a new `withPaginationParams` helper as part of this, to DRY up how pagination params are provided to API calls.
- Made the default "per page" value an app global constant.
- Moved all the request builders into a separate `apiRequestBuilders` service.
> Web: refactor the huge `hubApiService`

- platform-hub-api/app/models/kubernetes_token.rb
This commit also wraps the action in a lock to prevent overwriting in the case of simultaneous updates.
> Backend: de-dupe groups when escalating privilege for a token

- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/app.run.js
- platform-hub-web/src/app/shared/hub-api/api-helpers.factory.js
- platform-hub-web/src/app/shared/hub-api/api-pagination.factory.js
- platform-hub-web/src/app/shared/hub-api/api-request-builders.factory.js
- platform-hub-web/src/app/shared/hub-api/hub-api.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
You can now control the number of items returned per page in certain views by adding the `per_page=XX` query parameter to the URL.
The following views support this:
- Users list
- Kube groups list
- Kube namespaces list
- Kube robot tokens list
> Web: allow `per_page` override on certain views

- platform-hub-api/app/controllers/kubernetes/clusters_controller.rb
- platform-hub-api/app/serializers/kubernetes_cluster_serializer.rb
- platform-hub-api/db/migrate/20180216141957_add_aws_region_to_kubernetes_cluster.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/kubernetes/clusters_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/namespaces_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-detail.html
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-list.html
This allows us to support multiple Kubernetes clusters within the same AWS account ID, since we can now differentiate them by region. We'll be using this capability in upcoming costs reports work.
> Add `aws_region` to `KubernetesCluster` records

- platform-hub-api/app/services/costs/report_results_generator_service.rb
This time, make sure to initialise the `:total` value.
> Backend: another fix for initialisation of accumulation entries when generating costs reports

- platform-hub-api/spec/lib/hash_rollup_spec.rb
This confirms some expected behaviour when handling missing values / sub hashes.
> Backend: add extra test case for HashRollup

- platform-hub-api/app/services/costs/metrics_data_service.rb
For cases where multiple metrics exist per day per cluster per namespace.
> Backend: add a guard for dup metrics in costs reports generation

- platform-hub-api/app/jobs/help_search_index_ensurer_job.rb
- platform-hub-api/app/services/help_search_index_ensurer_job_trigger_service.rb
- platform-hub-api/lib/tasks/help_search.rake
The provided trigger can be run continuously to add the job to the queue, which checks to see if either the index doesn't yet exist or it's empty, at which point it performs a full reindex.
> Backend: background job to ensure the help search index is ready

- platform-hub-api/app/controllers/pinned_help_entries_controller.rb
- platform-hub-api/app/services/help_search_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/pinned_help_entries_controller_spec.rb
- platform-hub-api/spec/routing/pinned_help_entries_routing_spec.rb
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/docs-sources/docs-sources.module.js
- platform-hub-web/src/app/docs-sources/pinned-help-entries-form.component.js
- platform-hub-web/src/app/docs-sources/pinned-help-entries-form.html
- platform-hub-web/src/app/help/search/search.component.js
- platform-hub-web/src/app/help/search/search.html
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/model.module.js
- platform-hub-web/src/app/shared/model/pinned-help-entries.js
This list is managed in a new admin section - 'Pinned Help Entries' in the admin nav section.
This list is ordered.
> Hub admins can pin help entries to the top of the help search page

- platform-hub-api/app/controllers/help_controller.rb
- platform-hub-api/app/services/help_search_service.rb
- platform-hub-api/app/services/help_search_stats_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/help_controller_spec.rb
- platform-hub-api/spec/routing/help_routing_spec.rb
- platform-hub-api/spec/services/help_search_stats_service_spec.rb
- platform-hub-web/src/app/help/search/search.component.js
- platform-hub-web/src/app/help/search/search.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
The top 20 popular searches are shown on the help search page when no query has been made. (It will be shown under the suggestions (aka pinned items).
Example:
> Help search: count queries and result sizes and show on help search page

- platform-hub-api/app/services/help_search_service.rb
Rationale: a Q&A entry or support request form will likely be more relevant to a user of the hub. So this change ensures that these two types of results show up higher, as long as the initial relevance (based on title and content matches) is high also.
> Help search: Q&As and support requests will show up higher if more relevant

- platform-hub-api/app/models/project.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/models/announcement_spec.rb
- platform-hub-api/spec/models/docs_source_spec.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
- platform-hub-api/spec/models/project_spec.rb
- platform-hub-web/src/app/projects/projects-form.html
… since we use this as a first class identifier in billing, etc.
As part of this change I've also added some extra checks in the various specs that check for readonly attribute behaviour.
> Project shortname is now readonly

- platform-hub-api/app/controllers/docker_repos_controller.rb
- platform-hub-api/app/models/docker_repo.rb
- platform-hub-api/app/serializers/docker_repo_serializer.rb
- platform-hub-api/db/migrate/20181109123528_add_provider_to_docker_repos.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/docker_repos_controller_spec.rb
- platform-hub-api/spec/factories/docker_repos.rb
- platform-hub-api/spec/models/docker_repo_spec.rb
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-form.html
- platform-hub-web/src/app/projects/projects-detail.html
Currently only 'ECR', but this allows us to potentially support others.
> Docker repos: set a `provider` on the repo record / resource

- .drone.yml
- platform-hub-api/Gemfile.lock
- platform-hub-api/app/models/ability.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-web/package.json
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/projects-list.component.js
- platform-hub-web/src/app/projects/projects-list.component.spec.js
- platform-hub-web/src/app/projects/projects-list.html
- platform-hub-web/src/app/shared/model/projects.js
Users visiting the Projects page have difficulty finding their projects, as they have to scroll through a long list of projects which includes projects of which they are not members. See ticket [#2025](https://github.com/UKHomeOffice/application-container-platform-board/issues/2025) for more information.
I have organised the list of projects on the Projects page so that it prioritises and highlights the user's projects at the top of the list with all other projects greyed out (sorted alphabetically). This includes changes to the projects-list view and the addition of tests. 
In **projects-list.component.html**: To highlight the user’s projects, I added a ‘Member’ badge if the user is a member of the project and I also greyed out any projects of which the user is not a member:
In …
> Projects improvements

- .drone.yml
Amended how docker password secrets were referenced in drone.yml for web_latest_image_to_quay and api_latest_image_to_quay stages to pass build in drone v1.
> amending web and api latest image quay docker password envars

- .drone.yml
- README.md
- Amended pipeline to account for Docker Hub's changes to image limits.
- Amended the ReadMe to account for the fact that pushing tags on master branch no longer triggers deployment.
> modifying pipeline due to docker in docker images limit changes
