UKHomeOffice/platform-hub

- platform-hub-api/app/controllers/me_controller.rb
- platform-hub-api/app/models/user.rb
- platform-hub-api/config/routes.rb
- platform-hub-web/src/app/identities/identities-manager.component.js
- platform-hub-web/src/app/identities/identities-manager.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
Note: I'll rebase this against `master` once https://github.com/UKHomeOffice/platform-hub/pull/2 is merged.
> Ability to disconnect (and remove) a GitHub identity

- LICENSE
- platform-hub-api/.env.test
- platform-hub-api/Gemfile
- platform-hub-api/Gemfile.lock
- platform-hub-web/src/app/home/home.component.js
- platform-hub-web/src/app/home/home.html
- platform-hub-web/src/app/home/home.spec.js
See https://github.com/UKHomeOffice/platform-hub/pull/5
> Housekeeping

- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/shared/auth/auth-card.html
> Web: improve the UI of the project add team member section

- README.md
- platform-hub-api/README.md
- platform-hub-web/README.md
Would appreciate feedback on:
- Does it make sense?
- What would you like to see in these READMEs?
- How can we make it more concise?
- Anything else you want to talk about!
> Various README updates

- platform-hub-web/src/app/app.config.js
> Web: new color scheme

- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/help/faq.component.js
- platform-hub-web/src/app/help/faq.html
- platform-hub-web/src/app/help/help-centre.component.js
- platform-hub-web/src/app/help/help-centre.html
- platform-hub-web/src/app/help/help.module.js
- platform-hub-web/src/app/home/home.component.js
- platform-hub-web/src/app/home/home.html
- platform-hub-web/src/app/home/home.module.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/layout/shell.html
> Web: new Help centre with an initial FAQ section

- platform-hub-web/src/app/shared/auth/auth-card.component.js
- platform-hub-web/src/app/shared/auth/auth-card.html
The auth card should now show that the user is not logged in anymore when the session has timed out.
> Web: improve the auth status refreshing in the nav menu

- README.md
- platform-hub-web/README.md
See the [rendered README.md file](https://github.com/UKHomeOffice/platform-hub/blob/document-release-process/README.md#platform-hub--the-software-powering-the-hoddat-paas-hub) for the main change.
> README improvements + document the release and versioning process

- platform-hub-api/app/controllers/me_controller.rb
- platform-hub-api/app/models/user.rb
- platform-hub-api/app/models/user_flags.rb
- platform-hub-api/app/serializers/user_flags_serializer.rb
- platform-hub-api/app/serializers/user_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20170413124233_create_user_flags.rb
- platform-hub-api/db/migrate/20170418140933_add_scopes_to_users.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/me_controller_spec.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/controllers/users_controller_spec.rb
- platform-hub-api/spec/models/user_spec.rb
- platform-hub-api/spec/routing/me_routing_spec.rb
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/home/home.component.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/onboarding/hub-setup.component.js
- platform-hub-web/src/app/onboarding/hub-setup.html
- platform-hub-web/src/app/onboarding/onboarding.module.js
- platform-hub-web/src/app/shared/auth/auth-card.component.js
- platform-hub-web/src/app/shared/auth/auth-card.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/me.js
- platform-hub-web/src/app/shared/onboarding-trigger.factory.js
- platform-hub-web/src/app/shared/shared.module.js
**TODO:**
- ~~Allow platform theme resources to be scoped based on the user's new scope~~ _will do a separate PR_
- ~~Allow support request templates to be scoped based on the user's new scope~~ _will do a separate PR_
> New hub onboarding/setup flow

- platform-hub-api/app/controllers/support_request_templates_controller.rb
- platform-hub-api/app/serializers/support_request_template_serializer.rb
- platform-hub-api/db/migrate/20170420134436_add_user_scope_to_support_request_template.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/support_request_templates_controller_spec.rb
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-detail.html
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-form.component.js
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-form.html
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-list.html
- platform-hub-web/src/app/help/support/requests/support-requests-overview.component.js
- platform-hub-web/src/app/help/support/requests/support-requests-overview.html
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-form.component.js
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-form.html
- platform-hub-web/src/app/platform-themes/platform-themes-page.component.js
- platform-hub-web/src/app/platform-themes/platform-themes-page.html
- platform-hub-web/src/app/shared/model/model.module.js
- platform-hub-web/src/app/shared/model/user-scopes.js
Depends on https://github.com/UKHomeOffice/platform-hub/pull/40
> Scoping of resources (in platform themes) and support requests

- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/shared/auth/auth-card.html
> Web: prompt the user if they haven't completed either the hub or services onboarding

- platform-hub-api/app/controllers/concerns/authentication.rb
- platform-hub-web/src/app/app-settings/app-settings-form.component.js
- platform-hub-web/src/app/app-settings/app-settings-form.html
- platform-hub-web/src/app/onboarding/services-onboarding.html
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/identities/identities-list.html
- platform-hub-web/src/app/shared/model/app-settings.js
- platform-hub-web/src/app/shared/model/identities.js
These are the services that are not currently connected in the hub, but are still available to users of the platform.
> Ability to specify and show the other managed services provided to users

- platform-hub-api/app/controllers/contact_lists_controller.rb
- platform-hub-api/app/models/contact_list.rb
- platform-hub-api/app/models/hash_record.rb
- platform-hub-api/app/serializers/contact_list_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/contact_lists_controller_spec.rb
- platform-hub-api/spec/factories/contact_lists.rb
- platform-hub-api/spec/factories/hash_records.rb
- platform-hub-api/spec/models/contact_list_spec.rb
- platform-hub-api/spec/models/identity_spec.rb
- platform-hub-api/spec/models/project_spec.rb
- platform-hub-api/spec/routing/contact_lists_routing_spec.rb
- platform-hub-web/src/app/app-settings/app-settings-form.component.js
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/contact-lists/contact-list-form.component.js
- platform-hub-web/src/app/contact-lists/contact-list-form.html
- platform-hub-web/src/app/contact-lists/contact-lists.module.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/contact-lists.js
- platform-hub-web/src/app/shared/model/model.module.js
To be used later for things like global announcements.
> Admins can manage a global contacts list

- platform-hub-api/Gemfile
- platform-hub-api/Gemfile.lock
- platform-hub-api/app/controllers/announcements_controller.rb
- platform-hub-api/app/controllers/concerns/api_json_error_handler.rb
- platform-hub-api/app/controllers/platform_themes_controller.rb
- platform-hub-api/app/controllers/projects_controller.rb
- platform-hub-api/app/controllers/support_request_templates_controller.rb
- platform-hub-api/app/models/ability.rb
- platform-hub-api/app/models/announcement.rb
- platform-hub-api/app/models/audit.rb
- platform-hub-api/app/serializers/announcement_serializer.rb
- platform-hub-api/app/serializers/base_serializer.rb
- platform-hub-api/app/serializers/contact_list_serializer.rb
- platform-hub-api/app/serializers/identity_serializer.rb
- platform-hub-api/app/serializers/platform_theme_serializer.rb
- platform-hub-api/app/serializers/project_membership_serializer.rb
- platform-hub-api/app/serializers/project_serializer.rb
- platform-hub-api/app/serializers/support_request_template_serializer.rb
- platform-hub-api/app/serializers/user_flags_serializer.rb
- platform-hub-api/app/serializers/user_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20170602101700_create_announcements.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/announcements_controller_spec.rb
- platform-hub-api/spec/factories/announcements.rb
- platform-hub-api/spec/factories/users.rb
- platform-hub-api/spec/models/announcement_spec.rb
- platform-hub-api/spec/routing/announcements_routing_spec.rb
- platform-hub-api/spec/support/time_helpers.rb
UI + delivery of announcements will be built on top of this.
> Initial API for showing and managing announcements

- platform-hub-api/app/models/announcement.rb
- platform-hub-api/spec/controllers/announcements_controller_spec.rb
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.html
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.component.js
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
- platform-hub-web/src/app/app.scss
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-form.html
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-form.html
- platform-hub-web/src/app/shared/model/announcements.js
- platform-hub-web/src/app/shared/ui/form-field.html
See individual commits for details.
> Various tweaks / improvements (announcements mainly)

- platform-hub-api/app/services/announcements_processor_service.rb
- platform-hub-api/app/views/announcement_mailer/announcement_email.html.erb
- platform-hub-api/spec/mailers/announcement_mailer_spec.rb
- platform-hub-api/spec/services/announcements_processor_service_spec.rb
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.component.js
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.html
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.component.js
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/identities/identities-list.html
- platform-hub-web/src/app/shared/model/announcements.js
- platform-hub-web/src/index.html
> Various tweaks (mostly UI and user facing)

- platform-hub-api/app/controllers/me_controller.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20170626134741_add_agreed_to_terms_of_service_to_user_flags.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/me_controller_spec.rb
- platform-hub-api/spec/routing/me_routing_spec.rb
- platform-hub-web/src/app/app-settings/app-settings-form.html
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/onboarding/onboarding.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/app-settings.js
- platform-hub-web/src/app/shared/model/me.js
- platform-hub-web/src/app/shared/onboarding-trigger.factory.js
- platform-hub-web/src/app/terms-of-service/terms-of-service.component.js
- platform-hub-web/src/app/terms-of-service/terms-of-service.html
- platform-hub-web/src/app/terms-of-service/terms-of-service.module.js
As an admin, I would like to define a Terms of Service for users of the hub.
As a user, I would like to agree to the Terms of Service before I start using the features in the hub (i.e. when I first log in), and I want a link to the terms of service page available to me.
> Terms of service flows

- platform-hub-web/src/app/help/support/request-templates/support-request-templates-detail.html
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-form.html
- platform-hub-web/src/app/help/support/request-templates/support-request-templates-list.html
- platform-hub-web/src/app/help/support/requests/support-requests-overview.html
See individual commits for details
> Support requests UI tweaks

- platform-hub-api/app/controllers/projects_controller.rb
- platform-hub-api/app/serializers/project_serializer.rb
- platform-hub-api/db/migrate/20170628103710_add_cost_centre_code_to_projects.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/factories/projects.rb
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/projects-form.html
- platform-hub-web/src/app/projects/projects-list.html
Currently only viewable by admins and project managers (for their own projects).
> Admins can now specify a "cost centre code" on projects

- platform-hub-api/README.md
Updated the package dependency list for the Platform Hub API, including installation instructions for various OS distributions.
> [Platform Hub API] README.md dependency list updates

- platform-hub-web/src/app/contact-lists/contact-lists-form.component.js
- platform-hub-web/src/app/contact-lists/contact-lists-list.html
Fixed a display bug where contact list emails are hidden if any record occurs more than once.
> [PlatformHub][Web] Contact List display bug

- platform-hub-api/README.md
- platform-hub-web/src/app/kubernetes-tokens/kubernetes-tokens-form.component.js
- platform-hub-web/src/app/kubernetes-tokens/kubernetes-tokens-list.component.js
- platform-hub-web/src/app/kubernetes-tokens/kubernetes-tokens-list.html
> Web: fixes for Kubernetes tokens UI

- platform-hub-web/src/app/help/support/request-templates/support-request-templates-detail.html
- platform-hub-web/src/app/help/support/requests/support-requests-form.html
- platform-hub-web/src/app/help/support/requests/support-requests-overview.html
- platform-hub-web/src/app/home/home.html
- platform-hub-web/src/app/platform-themes/editor/platform-themes-editor-list.html
- platform-hub-web/src/app/platform-themes/platform-themes-page.html
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/projects-list.html
We now better handle paragraphs of text that contain newlines.
> Web: fix formatting for description fields

- platform-hub-api/app/models/announcement_template.rb
- platform-hub-api/app/services/announcement_template_formatter_service.rb
- platform-hub-api/db/migrate/20170727103721_change_description_null_on_announcement_templates.rb
- platform-hub-api/db/structure.sql
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.html
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
- platform-hub-web/src/app/announcements/templates/announcement-templates-form.component.js
- platform-hub-web/src/app/announcements/templates/announcement-templates-form.html
- platform-hub-web/src/app/contact-lists/contact-lists-form.component.js
- platform-hub-web/src/app/contact-lists/contact-lists-form.html
- platform-hub-web/src/app/shared/ui/ui.module.js
- platform-hub-web/src/app/shared/ui/validate-emails.directive.js
Please see individual commits for details
> Various tweaks and updates relating to announcement templates

- platform-hub-web/src/app/feature-flags/feature-flags-form.component.js
- platform-hub-web/src/app/feature-flags/feature-flags-form.html
- platform-hub-web/src/app/home/home.html
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/onboarding/services-onboarding.component.js
- platform-hub-web/src/app/onboarding/services-onboarding.html
- platform-hub-web/src/app/shared/model/feature-flags.js
Please see individual commits for details
> Some tweaks

- platform-hub-api/app/models/announcement.rb
- platform-hub-api/app/services/announcements_processor_service.rb
- platform-hub-api/spec/services/announcements_processor_service_spec.rb
- platform-hub-web/src/app/announcements/editor/announcements-editor-list.html
- platform-hub-web/src/app/shared/model/announcements.js
> Better handling of announcements with no delivery targets

- platform-hub-web/src/app/announcements/editor/announcements-editor-form.component.js
- platform-hub-web/src/app/home/home.html
Please see individual commit messages.
> Couple of important fixes

- platform-hub-api/app/services/kubernetes/changeset_service.rb
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-list.html
- platform-hub-web/src/app/kubernetes/kubernetes-tokens-sync.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.html
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/identities/identities-list.html
> UI improvements for Kube tokens management

- platform-hub-api/app/controllers/users_controller.rb
- platform-hub-api/app/models/ability.rb
- platform-hub-api/app/serializers/user_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/me_controller_spec.rb
- platform-hub-api/spec/controllers/users_controller_spec.rb
- platform-hub-api/spec/routing/users_routing_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.component.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/model/identities.js
- platform-hub-web/src/app/users/users-list.html
This ensures that we don't unnecessarily load up identities (and thus things like Kube tokens).
> Load identities separately to the Me resource

- platform-hub-api/app/controllers/allocations_controller.rb
- platform-hub-api/app/controllers/kubernetes/groups_controller.rb
- platform-hub-api/app/models/allocation.rb
- platform-hub-api/app/models/concerns/allocatable.rb
- platform-hub-api/app/models/concerns/allocation_receivable.rb
- platform-hub-api/app/serializers/allocation_serializer.rb
- platform-hub-api/app/serializers/service_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/allocations_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/groups_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/models/allocation_spec.rb
- platform-hub-api/spec/routing/allocations_routing_spec.rb
- platform-hub-api/spec/routing/kubernetes_groups_routing_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-groups-detail.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-groups-detail.html
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/kubernetes-groups.js
> More work on groups management (mainly: admins can view + delete)

- platform-hub-api/app/controllers/concerns/kubernetes_tokens_management.rb
- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/app/serializers/kubernetes_token_serializer.rb
- platform-hub-api/app/serializers/project_embedded_serializer.rb
- platform-hub-api/app/serializers/project_serializer.rb
- platform-hub-api/app/serializers/service_serializer.rb
- platform-hub-api/config/initializers/active_model_serializer.rb
- platform-hub-api/db/migrate/20171031164247_add_project_to_kubernetes_tokens.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/factories/kubernetes_clusters.rb
- platform-hub-api/spec/factories/kubernetes_tokens.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
- platform-hub-api/spec/services/kubernetes/token_file_service_spec.rb
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-list.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.component.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/kubernetes-tokens.js
In preparation for upcoming work on self serve of user tokens.
> Tokens are now assigned to projects (both user and robot) + some cleanup work

- platform-hub-api/app/controllers/concerns/kubernetes_groups_sub_collection.rb
- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/spec/models/kubernetes_token_spec.rb
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/kubernetes/kubernetes-groups-list.html
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-robot-tokens-list.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.component.spec.js
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-user-tokens-list.html
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/services/project-services-detail.component.js
- platform-hub-web/src/app/projects/services/project-services-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/identities/identities-list.component.js
- platform-hub-web/src/app/shared/identities/identities-list.html
- platform-hub-web/src/app/shared/model/kubernetes-groups.js
- platform-hub-web/src/app/shared/model/projects.js
The existing user tokens form has been completely repurposed to now be usable by both an admin and project manager.
> UI for managing Kubernetes user tokens within a project

- .drone.yml
- platform-hub-api/README.md
- platform-hub-api/config/boot.rb
- platform-hub-auth-proxy/README.md
- platform-hub-auth-proxy/local/.env
See individual commits for details.
> Build port fix + docker for mac host network fix

- platform-hub-api/app/services/project_memberships_service.rb
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/controllers/users_controller_spec.rb
- platform-hub-api/spec/services/project_memberships_service_spec.rb
> Backend: improve wording when using the term 'admin'

- platform-hub-api/app/controllers/users_controller.rb
- platform-hub-api/app/models/ability.rb
- platform-hub-api/app/models/user.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/costs_reports_controller_spec.rb
- platform-hub-api/spec/controllers/users_controller_spec.rb
- platform-hub-api/spec/factories/users.rb
- platform-hub-api/spec/rails_helper.rb
- platform-hub-api/spec/routing/users_routing_spec.rb
- platform-hub-api/spec/support/admin_authorization_helpers.rb
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/app.routes.spec.js
- platform-hub-web/src/app/app.run.js
- platform-hub-web/src/app/costs-reports/costs-reports-detail.component.js
- platform-hub-web/src/app/costs-reports/costs-reports-detail.html
- platform-hub-web/src/app/costs-reports/costs-reports-list.component.js
- platform-hub-web/src/app/costs-reports/costs-reports-list.html
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/role-checker.service.js
- platform-hub-web/src/app/users/users-list.component.js
- platform-hub-web/src/app/users/users-list.html
Currently only granted read access to the costs reports listing and details pages.
> New 'limited admin' role

- platform-hub-api/Gemfile
- platform-hub-api/Gemfile.lock
- platform-hub-api/app/controllers/users_controller.rb
- platform-hub-api/spec/controllers/users_controller_spec.rb
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/ui/paginated-list.directive.js
- platform-hub-web/src/app/shared/ui/paginated-list.html
- platform-hub-web/src/app/shared/ui/pagination-toolbar.component.js
- platform-hub-web/src/app/shared/ui/pagination-toolbar.html
- platform-hub-web/src/app/shared/ui/ui.module.js
- platform-hub-web/src/app/users/users-list.component.js
- platform-hub-web/src/app/users/users-list.html
This establishes the infrastructure/components for pagination throughout the API and web app.
Currently only the /users API (and corresponding page on the hub) is paginated. More to come in future commmits.
> Initial implementation of server side pagination

- platform-hub-api/app/controllers/costs_reports_controller.rb
- platform-hub-api/app/services/costs_and_resources_analysis_service.rb
- platform-hub-api/app/services/costs_report_generator_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/costs_reports_controller_spec.rb
- platform-hub-api/spec/routing/costs_reports_routing_spec.rb
- platform-hub-web/package.json
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/app.scss
- platform-hub-web/src/app/costs-reports/costs-and-resources-analysis.component.js
- platform-hub-web/src/app/costs-reports/costs-and-resources-analysis.html
- platform-hub-web/src/app/costs-reports/costs-reports-detail.html
- platform-hub-web/src/app/costs-reports/costs-reports-form.component.js
- platform-hub-web/src/app/costs-reports/costs-reports-form.html
- platform-hub-web/src/app/costs-reports/costs-reports-list.component.js
- platform-hub-web/src/app/costs-reports/costs-reports-list.html
- platform-hub-web/src/app/costs-reports/costs-reports.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/costs-reports.js
- platform-hub-web/src/app/shared/project-bill-breakdown-table.html
- platform-hub-web/yarn.lock
Currently only accessible by hub admins.
This is the first step towards a more elaborate tool for finely analysing a project's costs and resource usage per cluster.
For now this focuses on using the exact same data used for generating costs reports (billing + metrics) to show resource utilisation for each *namespace* of a project.
> Initial tool for analysing costs and resource usage for a project

- platform-hub-api/app/controllers/kubernetes/clusters_controller.rb
- platform-hub-api/app/models/kubernetes_cluster.rb
- platform-hub-api/app/models/kubernetes_group.rb
- platform-hub-api/app/models/kubernetes_token.rb
- platform-hub-api/app/serializers/kubernetes_cluster_serializer.rb
- platform-hub-api/db/migrate/20180221130735_add_groups_index_to_kubernetes_token.rb
- platform-hub-api/db/migrate/20180221145217_add_aliases_to_kubernetes_clusters.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/kubernetes/clusters_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/namespaces_controller_spec.rb
- platform-hub-api/spec/controllers/kubernetes/tokens_controller_spec.rb
- platform-hub-api/spec/controllers/projects_controller_spec.rb
- platform-hub-api/spec/controllers/services_controller_spec.rb
- platform-hub-api/spec/models/kubernetes_cluster_spec.rb
- platform-hub-api/spec/models/kubernetes_group_spec.rb
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.component.js
- platform-hub-web/src/app/announcements/editor/announcements-editor-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-detail.html
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-form.component.js
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-form.html
- platform-hub-web/src/app/kubernetes/kubernetes-clusters-list.html
- platform-hub-web/src/app/shared/hub-api/api-request-builders.factory.js
- platform-hub-web/src/app/shared/ui/chips-helpers.factory.js
- platform-hub-web/src/app/shared/ui/ui.module.js
---
This PR also includes some improvements – see the individual commits for details.
> Support multiple unique aliases for Kubernetes clusters

- .drone.yml
- changed the docker version for good measure
- but more important changed the --link name as it was producing conflict messages on the docker daemon logs
> Drone Build

- .drone.yml
- platform-hub-api/Dockerfile
- platform-hub-api/Gemfile.lock
This "fixes" some security vulnerabilities (though not for anything we're directly using / affected by).
> Backend: Update some deps

- platform-hub-web/src/app/shared/kubernetes-token-value.component.js
- platform-hub-web/src/app/shared/kubernetes-token-value.html
… only when you can actually see the whole token value.
> Web: copy button to copy token value

- platform-hub-api/config/routes.rb
- platform-hub-api/spec/routing/users_routing_spec.rb
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
> Escape query string when searching for a user

- platform-hub-api/bin/elasticsearch/create
Disables X-Pack features that are not needed locally.
> Backend: fix the local ElasticSearch instance

- platform-hub-api/app/models/docs_source.rb
- platform-hub-api/bin/elasticsearch/README.md
- platform-hub-api/bin/elasticsearch/create
- platform-hub-api/bin/postgres/README.md
- platform-hub-api/spec/jobs/tokens_sync_job_spec.rb
- platform-hub-api/spec/models/docs_source_spec.rb
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/docs-sources/docs-sources.module.js
> Various fixes pulled out of the docs indexing branch

- platform-hub-api/Gemfile.lock
Note: this only affects development, not production.
> Bump ffi gem to fix security vulnerability

- platform-hub-api/app/controllers/docs_sources_controller.rb
- platform-hub-api/app/jobs/docs_sync_job.rb
- platform-hub-api/app/services/docs/docs_sync_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/docs_sources_controller_spec.rb
- platform-hub-api/spec/jobs/docs_sync_job_spec.rb
- platform-hub-api/spec/routing/docs_sources_routing_spec.rb
- platform-hub-web/src/app/docs-sources/docs-sources-list.component.js
- platform-hub-web/src/app/docs-sources/docs-sources-list.html
- platform-hub-web/src/app/shared/hub-api/api-request-builders.factory.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/docs-sources.js
See individual commits for details.
> Docs sync actions + improvements

- platform-hub-api/app/controllers/docs_sources_controller.rb
- platform-hub-api/app/serializers/docs_source_entry_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/docs_sources_controller_spec.rb
- platform-hub-api/spec/routing/docs_sources_routing_spec.rb
- platform-hub-web/src/app/docs-sources/docs-sources-detail.component.js
- platform-hub-web/src/app/docs-sources/docs-sources-detail.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/docs-sources.js
> Show all doc entries for docs sources

- platform-hub-api/app/controllers/qa_entries_controller.rb
- platform-hub-api/app/models/qa_entry.rb
- platform-hub-api/app/serializers/qa_entry_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20180927152425_create_qa_entries.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/qa_entries_controller_spec.rb
- platform-hub-api/spec/factories/qa_entries.rb
- platform-hub-api/spec/models/qa_entry_spec.rb
- platform-hub-api/spec/routing/qa_entries_routing_spec.rb
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/docs-sources/docs-sources-detail.component.js
- platform-hub-web/src/app/layout/shell.component.js
- platform-hub-web/src/app/qa-entries/qa-entries-detail.component.js
- platform-hub-web/src/app/qa-entries/qa-entries-detail.html
- platform-hub-web/src/app/qa-entries/qa-entries-form.component.js
- platform-hub-web/src/app/qa-entries/qa-entries-form.html
- platform-hub-web/src/app/qa-entries/qa-entries-list.component.js
- platform-hub-web/src/app/qa-entries/qa-entries-list.html
- platform-hub-web/src/app/qa-entries/qa-entries.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/icons.factory.js
- platform-hub-web/src/app/shared/model/model.module.js
- platform-hub-web/src/app/shared/model/qa-entries.js
I'll hook this up to the help search in a separate PR.
> Hub admins can manage Q&A entries

- platform-hub-api/app/controllers/help_controller.rb
- platform-hub-api/app/controllers/pinned_help_entries_controller.rb
- platform-hub-api/app/services/docs/docs_source_sync_base.rb
- platform-hub-api/app/services/help_search_service.rb
- platform-hub-api/app/services/help_search_stats_service.rb
- platform-hub-api/app/services/help_search_status_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/spec/controllers/help_controller_spec.rb
- platform-hub-api/spec/controllers/pinned_help_entries_controller_spec.rb
- platform-hub-api/spec/routing/help_routing_spec.rb
- platform-hub-api/spec/services/help_search_stats_service_spec.rb
- platform-hub-web/src/app/docs-sources/pinned-help-entries-form.component.js
- platform-hub-web/src/app/docs-sources/pinned-help-entries-form.html
- platform-hub-web/src/app/help/search/search.component.js
- platform-hub-web/src/app/help/search/search.html
- platform-hub-web/src/app/help/search/search.scss
- platform-hub-web/src/app/layout/shell.html
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
Please see individual comments for details.
More to come in part 2 (breaking this up early so we can start reviewing).
> Various improvements and fixes for the help search and related features (part 1)

- platform-hub-web/src/app/docs-sources/docs-sources-detail.html
- platform-hub-web/src/app/docs-sources/docs-sources-list.html
Like the actual source config + fetch status / details.
> Web: add more info about docs sources

- platform-hub-api/app/controllers/docker_repos_controller.rb
- platform-hub-api/app/models/ability.rb
- platform-hub-api/app/models/docker_repo.rb
- platform-hub-api/app/models/project.rb
- platform-hub-api/app/models/service.rb
- platform-hub-api/app/serializers/docker_repo_serializer.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20181101135115_create_docker_repos.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/docker_repos_controller_spec.rb
- platform-hub-api/spec/factories/docker_repos.rb
- platform-hub-api/spec/models/docker_repo_spec.rb
- platform-hub-api/spec/routing/docker_repos_routing_spec.rb
- platform-hub-api/spec/routing/services_routing_spec.rb
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.routes.js
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-form.component.js
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-form.html
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/projects.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/projects.js
Note: this is not yet functional:
- It lays out the barebones UI and hub backend for supporting Docker Repo management for projects.
- In upcoming work we'll hook this up to the backend integration service (via a message bus) and add access management.
> Initial work on Docker Repos support

- platform-hub-api/app/controllers/docker_repos_controller.rb
- platform-hub-api/app/controllers/services_controller.rb
- platform-hub-api/app/models/docker_repo.rb
- platform-hub-api/app/serializers/docker_repo_serializer.rb
- platform-hub-api/app/services/docker_repo_access_policy_service.rb
- platform-hub-api/config/routes.rb
- platform-hub-api/db/migrate/20181114155258_add_access_to_docker_repos.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/docker_repos_controller_spec.rb
- platform-hub-api/spec/models/docker_repo_spec.rb
- platform-hub-api/spec/routing/docker_repos_routing_spec.rb
- platform-hub-api/spec/services/docker_repo_access_policy_service_spec.rb
- platform-hub-web/package.json
- platform-hub-web/src/app/app.module.js
- platform-hub-web/src/app/app.scss
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-access-form-popup.controller.js
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-access-form-popup.html
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-access-form-popup.service.js
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-form.html
- platform-hub-web/src/app/projects/projects-detail.component.js
- platform-hub-web/src/app/projects/projects-detail.html
- platform-hub-web/src/app/projects/projects.module.js
- platform-hub-web/src/app/shared/hub-api/hub-api.service.js
- platform-hub-web/src/app/shared/model/projects.js
- platform-hub-web/yarn.lock
Will be hooked up to the backend integration service in upcoming PR(s).
> Initial flows for viewing and requesting updates to the access policy for Docker repos

- platform-hub-api/app/serializers/docker_repo_serializer.rb
- platform-hub-api/app/services/docker_repo_access_policy_service.rb
- platform-hub-api/app/services/docker_repo_lifecycle_service.rb
- platform-hub-api/app/services/ecr_agent_results_worker.rb
- platform-hub-api/db/migrate/20181204101525_rename_url_to_base_uri_in_docker_repos.rb
- platform-hub-api/db/structure.sql
- platform-hub-api/spec/controllers/docker_repos_controller_spec.rb
- platform-hub-api/spec/models/docker_repo_spec.rb
- platform-hub-api/spec/services/docker_repo_access_policy_service_spec.rb
- platform-hub-api/spec/services/docker_repo_lifecycle_service_spec.rb
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-access-form-popup.controller.js
- platform-hub-web/src/app/projects/docker-repos/project-docker-repos-access-form-popup.html
- platform-hub-web/src/app/projects/projects-detail.html
> Docker repos tweaks and improvements

- .drone.yml
- platform-hub-web/src/app/shared/model/announcement-templates.js
- platform-hub-web/src/app/shared/model/announcements.js
- platform-hub-web/src/app/shared/model/app-settings.js
- platform-hub-web/src/app/shared/model/feature-flags.js
- platform-hub-web/src/app/shared/model/kubernetes-clusters.js
- platform-hub-web/src/app/shared/model/me.js
- platform-hub-web/src/app/shared/model/platform-themes.js
- platform-hub-web/src/app/shared/model/projects.js
- platform-hub-web/yarn.lock
Ran auto update, amended .setTimeout method to $timeout service in files to resolve update conflict.
Amended drone.yml to complete pipeline for frontend packages update.
> Updated frontend packages

- .drone.yml
add puma vulns to Anchore whitelist
> add puma vulns to Anchore whitelist

- README.md
Quick typo fix in main README file.
```
re-requeistics -> Prerequisites
```
Thanks.
> Typo Fix in README.md
